
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 15 20:32:28 BOT 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Literal = 3;
  public static final int Tabulacion = 2;
  public static final int ERROR = 5;
  public static final int error = 1;
  public static final int Salto = 4;
  public static final int Nota = 6;
  public static final int EOF = 0;
}

